// Copyright (c) 2022 Andrea Ballestrazzi
#ifndef CATCH2_GMOCK_LISTENER_HPP
#define CATCH2_GMOCK_LISTENER_HPP

#if defined(USE_CATCH2_AS_TESTING_FRAMEWORK) && defined(USE_GMOCK)

#endif // USE_CATCH2_AS_TESTING_FRAMEWORK && USE_GMOCK
#endif // !CATCH2_GMOCK_LISTENER_HPP
