# Copyright (C) 2023 Andrea Ballestrazzi

name: Linux Release Build

on:
  push:
    branches-ignore:
      - "main"

jobs:
  gcc-12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: (RPI_GC) Check changed files
        id: RPI_GC-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/**
            test/**
            scripts/**
            toolchains/**
            .github/workflows/aarch64-linux-build.yml


      - name: Setup Microsoft GSL
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          git clone --depth 1 --branch v4.0.0 https://github.com/microsoft/GSL.git
          cd GSL
          mkdir build
          cd build
          cmake ..
          sudo make
          sudo make install

      - name: Setup Catch2
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          git clone --depth 1 --branch v3.4.0 https://github.com/catchorg/Catch2.git
          cd Catch2
          mkdir build
          sudo cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install -j 22

      - name: Compiler Setup
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-12-aarch64-linux-gnu g++-12-aarch64-linux-gnu autoconf-archive pkg-config m4 libtool automake autoconf gcc-13 g++-13 -y

      - name: Linux Release Build
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          mkdir buildLinux
          cd scripts
          chmod +x linux-perform-release.sh
          ./linux-perform-release.sh
