# Copyright (C) 2023 Andrea Ballestrazzi

name: aarch64 Build

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

env:
  BUILD_TYPE: Release

jobs:
  aarch64-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest
            cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:

      - uses: actions/checkout@v3

      - name: (RPI_GC) Check changed files
        id: RPI_GC-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/rpi_gc/**

      - uses: pguyot/arm-runner-action@v2
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        with:
          image_additional_mb: 1024
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          commands: |
              kernel_version=`apt list --installed | grep raspberrypi-kernel | awk '{ print $2 }' | sed -e 's|1:||g'`
              arch=`apt list --installed | grep raspberrypi-kernel | awk '{ print $3 }'`
              wget -q http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_${kernel_version}_${arch}.deb
              dpkg --install raspberrypi-kernel-headers_${kernel_version}_${arch}.deb
              apt-get update -y --allow-releaseinfo-change
              apt-get install --no-install-recommends -y libasound2-dev gcc libc6-dev git autoconf-archive pkg-config m4 libtool automake autoconf
              CMAKE_VERSION="3.24.3"
              curl -sSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.sh -o install-cmake.sh
              chmod +x install-cmake.sh
              ./install-cmake.sh --prefix=/usr/local --skip-license
              cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Wno-dev
              cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
              ./bin/test_app
