# Copyright (C) 2023 Andrea Ballestrazzi

name: aarch64 Linux Build

on:
  push:
    branches-ignore:
      - "main"
      # We don't need to run this workflow for branches that
      # updates only CI/CD scripts. We ignore those branches.
      - 'CI-UPDATE/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: (RPI_GC) Check changed files
        id: RPI_GC-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/**
            test/**

      - name: Compiler Setup
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu autoconf-archive pkg-config m4 libtool automake autoconf

      - name: Aarch64 Build
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          mkdir buildLinux
          cd scripts
          chmod +x aarch64-perform-release.sh
          ./aarch64-perform-release.sh
