# Copyright (C) 2022 Andrea Ballestrazzi

name: ARM Build and Tests

on:
   push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest
            cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          commands: |
              kernel_version=`apt list --installed | grep raspberrypi-kernel | awk '{ print $2 }' | sed -e 's|1:||g'`
              wget -q http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_${kernel_version}_${arch}.deb
              dpkg --install raspberrypi-kernel-headers_${kernel_version}_${arch}.deb
              apt-get update -y --allow-releaseinfo-change
              apt-get install --no-install-recommends -y libasound2-dev cmake gcc libc6-dev
              cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
