# Copyright (C) 2022 Andrea Ballestrazzi

name: ARM Build and Tests

on:
   push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        include:
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest
            cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          commands: |
              test `uname -m` = ${{ matrix.arch }}
              grep Model /proc/cpuinfo

      - name: CMake Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
