# Copyright (C) 2023 Andrea Ballestrazzi

name: Builds and Tests

on:
  push:
    branches-ignore:
      - main
# We don't need to run this workflow for branches that
# updates only CI/CD scripts. We ignore those branches.
      - 'CI-UPDATE/**'

env:
  BUILD_TYPE: Release

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Package configuration
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: sudo apt-get install autoconf-archive pkg-config m4 libtool automake autoconf

    - name: CMake Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Wno-dev
      env:
        CC:   gcc-12
        CXX:  g++-12

    - name: CMake Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Static Tests Run
      continue-on-error: true
      run: ${{github.workspace}}/bin/test_app --order rand [static]

    - name: Unit Tests Run
      continue-on-error: true
      run: ${{github.workspace}}/bin/test_app --order rand [unit]

    - name: Integration Tests Run
      continue-on-error: true
      run: ${{github.workspace}}/bin/test_app --order rand [integration]

    - name: Functional Tests Run
      continue-on-error: true
      run: ${{github.workspace}}/bin/test_app --order rand [functional]
