# Copyright (C) 2022 Andrea Ballestrazzi

name: Builds and Tests

on:
  push:
    branches-ignore:
      - main
# We don't need to run this workflow for branches that
# updates only CI/CD scripts. We ignore those branches.
      - 'CI-UPDATE/**'

env:
  BUILD_TYPE: Release

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.24.3'

      - name: Run clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.2
        with:
          scandir: '.'
          builddir: 'build'
          excludedirs: 'src/third-party,test/third-party'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'

  build_matrix:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: MacOS Compiler configuration
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew update
        brew install gcc@12

    - name: MacOS CMake Configure
      if: ${{ matrix.os == 'macos-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Wno-dev
      env:
        CC:   gcc-12
        CXX:  g++-12

    - name: CMake Configure
      if: ${{ matrix.os != 'macos-latest' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Wno-dev

    - name: CMake Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Static Tests Run
      run: ${{github.workspace}}/bin/test_app --order rand [static]

    - name: Unit Tests Run
      run: ${{github.workspace}}/bin/test_app --order rand [unit]

    - name: Integration Tests Run
      run: ${{github.workspace}}/bin/test_app --order rand [integration]

    - name: Functional Tests Run
      run: ${{github.workspace}}/bin/test_app --order rand [functional]
