# Copyright (C) 2022 Andrea Ballestrazzi

name: Builds and Tests

on:
  push:
    branches-ignore:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-node@v3

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: CMake Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: CMake Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Static Tests Run
      run: ${{github.workspace}}/bin/test_app --order rand [static]
