# Copyright (C) 2022 Andrea Ballestrazzi

# This workflow will increment softwares versions if the last
# push on the main branch contains changes in the softwares folders
# NOTE: This needs to exclude only-tests changes, as they don't
# change production code.
name: Increment Versions

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  push:
    branches:
      - 'update-increment-version-CI'

jobs:
  increment-version:
    runs-on: ubuntu-latest
    ##if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'update-increment-version-CI'
          fetch-depth: 0

      - name: Git initialization
        run: |
          git config user.name "IV_BOT"
          git config user.email "WinterWind33@users.noreply.github.com"

      # - name: Files and Folders initialization
      #   run: |
      #     mkdir tmp
      #     chmod +x .github/scripts/check-software-changes.sh

      - name: Retrieve changed files
        id: changed-files
        uses: tj-actions/changed-files@v33

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done

      # - name: (RPI_GC) Increment Version
      #   run: .github/scripts/check-software-changes.sh rpi_gc src/rpi_gc/rpi_gc-config-file.hpp

      # - name: Cleanup
      #   run: rm -f -r tmp
