# Copyright (C) 2023 Andrea Ballestrazzi

# This workflow will increment softwares versions if the last
# push on the main branch contains changes in the softwares folders
# NOTE: This needs to exclude only-tests changes, as they don't
# change production code.
name: Increment Versions

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

# For debugging purposes we trigger this job on all the branches
# that starts with "CI-UPDATE/IV-**"
  push:
    branches:
      - 'CI-UPDATE/IV-**'

env:
  RPI_GC_CONFIGURATION_FILE: src/rpi_gc/rpi_gc-config-file.hpp

jobs:
  increment-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/CI-UPDATE/IV-**'

    outputs:
      has_increased: ${{ steps.RPI_GC-increment-version.outputs.increased }}
      new_version: ${{ steps.RPI_GC-increment-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git initialization
        run: |
          git config user.name "IV_BOT"
          git config user.email "WinterWind33@users.noreply.github.com"

      - name: (RPI_GC) Check changed files
        id: RPI_GC-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src/rpi_gc/**

      - name: (RPI_GC) Increment Version
        id: RPI_GC-increment-version
        if: steps.RPI_GC-changed-files.outputs.any_changed == 'true'
        run: |
          mkdir tmp
          git checkout main
          git branch --set-upstream-to origin/main
          python3 .github/scripts/increment-version.py ${{env.RPI_GC_CONFIGURATION_FILE}} rpi_gc --patch
          git add ${{env.RPI_GC_CONFIGURATION_FILE}}
          git commit -m "[IV_BOT](Version Increment) Updated rpi_gc version to $(head -n 1 ./tmp/new_version.txt)."
          git push
          echo "$(head -n 1 ./tmp/new_version.txt)"
          echo "increased=true" >> $GITHUB_OUTPUT
          echo "version=$(head -n 1 ./tmp/new_version.txt)" >> $GITHUB_OUTPUT
          rm -r -f tmp

  create-git-tag:
    runs-on: ubuntu-latest
    needs: increment-version
    if: needs.increment-version.outputs.has_increased == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Git initialization
        run: |
          git config user.name "IV_BOT"
          git config user.email "WinterWind33@users.noreply.github.com"

      - name: Create Git Tag
        run: |
          git tag -a "v${{needs.increment-version.outputs.new_version}}" -m "Release v${{needs.increment-version.outputs.new_version}}"
          git push origin "v${{needs.increment-version.outputs.new_version}}"
